### PR TITLE
Fix potential dealock for register_serial_device and register_vsock_device

### LINKED ISSUE #218: register_serial_device(): Potential deadlock and potential panic
sha: https://github.com/intel/MigTD/commit/436786bfe6e2cf14cffaa4015d1ede18f290a6ab
File: src/devices/virtio_serial/src/lib.rs
Function: register_serial_device()
Description:
Potential deadlock due to double lock acquisition without guarantee of release between calls
```
98: lazy_static! {
99: static ref SERIAL_DEVICE: Mutex<Once<VirtioSerial>> = Mutex::new(Once::new());
100: }
101: 
102: pub fn register_serial_device(dev: VirtioSerial) -> Result<()> {
103: SERIAL_DEVICE.lock().call_once(|| dev);
104: SERIAL_DEVICE.lock().get_mut().unwrap().init()?;
105: Ok(())
106: }
```

### LINKED ISSUE #220: register_vsock_device(): Potential deadlock and potential panic
sha: https://github.com/intel/MigTD/commit/436786bfe6e2cf14cffaa4015d1ede18f290a6ab
File: src/devices/vsock/src/stream.rs
Function: register_vsock_device()
Description:
Potential deadlock due to double lock acquisition without guarantee of release between calls and potential panic due to unwrap() without checking if the value is Some. If the VSOCK_DEVICE is not properly initialized, this could lead to a panic.
```rust
49: pub fn register_vsock_device(dev: VsockDevice) -> Result {
50: VSOCK_DEVICE.lock().call_once(|| dev);
51: VSOCK_DEVICE.lock().get_mut().unwrap().transport.init()?;
52: Ok(())
```

### PR DESCRIPTION
**Pull request by liuw1**
Fix #218 and Fix #220

### CODE REVIEW

File: src/devices/virtio_serial/src/lib.rs [hunk 1]
```diff
@@ -100,8 +103,12 @@ lazy_static! {
 }
 
 pub fn register_serial_device(dev: VirtioSerial) -> Result<()> {
-    SERIAL_DEVICE.lock().call_once(|| dev);
-    SERIAL_DEVICE.lock().get_mut().unwrap().init()?;
+    let mut serial_device = SERIAL_DEVICE.lock();
+    serial_device.call_once(|| dev);
+    match serial_device.get_mut() {
```
Comment (gaojiaqi7) [inline src/devices/virtio_serial/src/lib.rs:108]: Please simplify this with `.unwrap_or(Err(VirtioSerialError::Initialization)).init()?`

File: src/devices/virtio_serial/src/lib.rs [hunk 2]
```diff
@@ -68,6 +70,7 @@ pub enum VirtioSerialError {
 impl Display for VirtioSerialError {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
         match self {
+            VirtioSerialError::InitializationError => write!(f, "Initialization"),
```
Comment (gaojiaqi7) [inline src/devices/virtio_serial/src/lib.rs:73]: Please rename to `VirtioSerialError::Initialization`

**Review by gaojiaqi7 — APPROVED** [review]
